import type { Answers, Step } from "./types";

/**
 * O funil do AlphaDog.
 *
 * A ordem importa: perguntas em blocos curtos, intercalados com interstícios de
 * prova social. Isso mantém o tutor engajado num questionário longo — é o padrão
 * que sustenta a conversão em funis desse tipo.
 *
 * Nada aqui é componente. Para mudar o funil, mude este arquivo.
 */

const isPuppy = (a: Answers) => a.petAge === "puppy";

export const BREEDS = [
  { value: "srd", label: "SRD (vira-lata)" },
  { value: "shih-tzu", label: "Shih Tzu" },
  { value: "poodle", label: "Poodle" },
  { value: "yorkshire", label: "Yorkshire" },
  { value: "lhasa-apso", label: "Lhasa Apso" },
  { value: "maltes", label: "Maltês" },
  { value: "pinscher", label: "Pinscher" },
  { value: "spitz-alemao", label: "Spitz Alemão (Lulu)" },
  { value: "bulldog-frances", label: "Bulldog Francês" },
  { value: "pug", label: "Pug" },
  { value: "beagle", label: "Beagle" },
  { value: "border-collie", label: "Border Collie" },
  { value: "golden-retriever", label: "Golden Retriever" },
  { value: "labrador", label: "Labrador" },
  { value: "pastor-alemao", label: "Pastor Alemão" },
  { value: "rottweiler", label: "Rottweiler" },
  { value: "pitbull", label: "Pit Bull" },
  { value: "husky", label: "Husky Siberiano" },
  { value: "dachshund", label: "Dachshund (salsicha)" },
  { value: "chihuahua", label: "Chihuahua" },
  { value: "outra", label: "Outra raça" },
] as const;

export const funnelSteps: readonly Step[] = [
  {
    key: "petAge",
    type: "list",
    title: "Qual a idade do seu cão?",
    subtitle: "O plano muda bastante conforme a fase de vida.",
    options: [
      { value: "puppy", label: "Filhote", hint: "Menos de 6 meses", icon: "🍼" },
      { value: "adolescent", label: "Adolescente", hint: "6 a 18 meses", icon: "🎾" },
      { value: "adult", label: "Adulto", hint: "1,5 a 7 anos", icon: "🦴" },
      { value: "senior", label: "Idoso", hint: "Mais de 7 anos", icon: "💤" },
    ],
  },
  {
    key: "petGender",
    type: "list",
    title: "Seu cão é macho ou fêmea?",
    options: [
      { value: "male", label: "Macho", icon: "♂️" },
      { value: "female", label: "Fêmea", icon: "♀️" },
    ],
  },
  {
    key: "petBreed",
    type: "dropdown",
    title: "Qual a raça do seu cão?",
    subtitle: "Cada raça aprende num ritmo diferente. SRD também conta.",
    placeholder: "Buscar raça...",
    options: BREEDS,
  },
  {
    key: "social-proof",
    type: "static",
    variant: "social-proof",
    title: "Você está em boa companhia",
    body: "Mais de 120 mil tutores já montaram o plano do seu cão com a gente — de filhote agitado a adulto teimoso.",
    bullets: [
      "94% relatam melhora clara em 4 semanas",
      "Sessões de 10 minutos, feitas em casa",
      "Método positivo, sem punição",
    ],
    cta: "Continuar",
  },
  {
    key: "motivation_to_start",
    type: "list",
    title: "O que te trouxe até aqui?",
    options: [
      { value: "new-dog", label: "Acabei de adotar ou comprar", icon: "🏠" },
      { value: "behavior", label: "Um comportamento está me incomodando", icon: "😤" },
      { value: "bond", label: "Quero me conectar melhor com ele", icon: "❤️" },
      { value: "basics", label: "Quero ensinar o básico direito", icon: "🎓" },
    ],
  },
  {
    key: "goal",
    type: "list",
    title: "Qual seu principal objetivo?",
    subtitle: "Escolha o que mais importa agora. Dá para ajustar depois.",
    options: [
      { value: "obedience", label: "Um cão obediente no dia a dia", icon: "✅" },
      { value: "fix-behavior", label: "Resolver um problema específico", icon: "🔧" },
      { value: "socialize", label: "Socializar com gente e outros cães", icon: "🐕" },
      { value: "tricks", label: "Ensinar comandos e truques", icon: "🎯" },
    ],
  },
  {
    key: "failed_to_train_dog",
    type: "statement",
    title: "O quanto você concorda?",
    statement: "Já tentei treinar meu cão antes e não deu certo.",
  },
  {
    key: "training_consistency",
    type: "statement",
    title: "E com esta?",
    statement: "Tenho dificuldade de manter constância no treino.",
  },
  {
    key: "training_fun_experience",
    type: "statement",
    title: "Mais uma",
    statement: "Quero que treinar seja divertido para nós dois.",
  },
  {
    key: "you-not-alone",
    type: "static",
    variant: "social-proof",
    title: "Você não está sozinho nisso",
    body: "8 em cada 10 tutores dizem já ter desistido de treinar antes de chegar aqui. O problema quase nunca é o cão — é não ter um plano na ordem certa.",
    cta: "Faz sentido",
  },
  {
    key: "refuse_pay_attention",
    type: "list",
    title: "Seu cão te ignora quando você chama?",
    options: [
      { value: "always", label: "Quase sempre", icon: "🙉" },
      { value: "outside", label: "Só na rua ou com distração", icon: "🌳" },
      { value: "sometimes", label: "De vez em quando", icon: "🤔" },
      { value: "never", label: "Ele costuma responder bem", icon: "👂" },
    ],
  },
  {
    key: "last_time_ignored_command",
    type: "list",
    title: "Quando foi a última vez que ele ignorou um comando?",
    options: [
      { value: "today", label: "Hoje", icon: "📍" },
      { value: "this-week", label: "Esta semana", icon: "📅" },
      { value: "this-month", label: "Este mês", icon: "🗓️" },
      { value: "rarely", label: "Raramente acontece", icon: "✨" },
    ],
  },
  {
    key: "puppy_feeding_problems",
    type: "list",
    title: "Como está a hora da comida?",
    subtitle: "Filhote costuma dar trabalho aqui.",
    showWhen: isPuppy,
    options: [
      { value: "too-fast", label: "Come rápido demais", icon: "💨" },
      { value: "picky", label: "Enjoa e recusa comida", icon: "🙅" },
      { value: "steals", label: "Rouba comida nossa", icon: "🍕" },
      { value: "fine", label: "Sem problema", icon: "👌" },
    ],
  },
  {
    key: "beg_for_treats",
    type: "list",
    title: "Ele pede comida na mesa?",
    options: [
      { value: "always", label: "Sempre, e insiste", icon: "🥺" },
      { value: "sometimes", label: "Às vezes", icon: "😐" },
      { value: "never", label: "Nunca", icon: "🚫" },
    ],
  },
  {
    key: "potty",
    type: "list",
    title: "E as necessidades?",
    options: [
      { value: "wrong-place", label: "Faz no lugar errado", icon: "😬" },
      { value: "learning", label: "Está aprendendo", icon: "📈" },
      { value: "outside-only", label: "Só na rua", icon: "🌳" },
      { value: "solved", label: "Já resolvido", icon: "✅" },
    ],
  },
  {
    key: "crate_trained",
    type: "list",
    title: "Ele aceita ficar sozinho no espaço dele?",
    showWhen: isPuppy,
    options: [
      { value: "yes", label: "Sim, tranquilo", icon: "😌" },
      { value: "cries", label: "Chora ou late", icon: "😰" },
      { value: "never-tried", label: "Nunca tentei", icon: "🤷" },
    ],
  },
  {
    key: "problems",
    type: "list",
    multiple: true,
    title: "O que mais te incomoda hoje?",
    subtitle: "Pode marcar quantos quiser.",
    options: [
      { value: "barking", label: "Late demais", icon: "📢" },
      { value: "pulling", label: "Puxa a guia", icon: "🦮" },
      { value: "jumping", label: "Pula nas pessoas", icon: "🙋" },
      { value: "chewing", label: "Destrói objetos", icon: "🪑" },
      { value: "separation", label: "Sofre quando fica sozinho", icon: "😢" },
      { value: "aggression", label: "Rosna ou avança", icon: "⚠️" },
      { value: "digging", label: "Cava tudo", icon: "🕳️" },
      { value: "none", label: "Nenhum desses", icon: "😇" },
    ],
  },
  {
    key: "cues",
    type: "list",
    multiple: true,
    title: "Quais comandos ele já sabe?",
    subtitle: "Só marque os que ele obedece de verdade.",
    options: [
      { value: "sit", label: "Senta", icon: "🪑" },
      { value: "stay", label: "Fica" },
      { value: "come", label: "Vem aqui" },
      { value: "down", label: "Deita" },
      { value: "paw", label: "Dá a pata" },
      { value: "heel", label: "Junto (na guia)" },
      { value: "none", label: "Nenhum ainda", icon: "🐣" },
    ],
  },
  {
    key: "behaviors_to_discipline",
    type: "list",
    multiple: true,
    title: "O que você quer melhorar primeiro?",
    options: [
      { value: "focus", label: "Atenção em você" },
      { value: "leash", label: "Passeio na guia" },
      { value: "guests", label: "Comportamento com visitas" },
      { value: "recall", label: "Voltar quando chamado" },
      { value: "calm", label: "Ficar calmo em casa" },
      { value: "car", label: "Andar de carro" },
    ],
  },
  {
    key: "almost-ready",
    type: "static",
    variant: "almost-ready",
    title: "Seu plano está tomando forma",
    body: "Com o que você já respondeu, dá para montar a base do programa. Faltam algumas perguntas sobre o temperamento dele.",
    cta: "Vamos lá",
  },
  {
    key: "fear_of_anxiety_in_new_environments",
    type: "list",
    title: "Como ele reage a lugares novos?",
    options: [
      { value: "curious", label: "Curioso e tranquilo", icon: "🧭" },
      { value: "cautious", label: "Desconfiado no começo", icon: "👀" },
      { value: "scared", label: "Fica com medo", icon: "😨" },
      { value: "overexcited", label: "Fica elétrico demais", icon: "⚡" },
    ],
  },
  {
    key: "stress_triggers",
    type: "list",
    multiple: true,
    title: "O que deixa ele estressado?",
    options: [
      { value: "loud-noises", label: "Barulho alto e fogos", icon: "🎆" },
      { value: "strangers", label: "Estranhos", icon: "👤" },
      { value: "other-dogs", label: "Outros cães", icon: "🐕" },
      { value: "alone", label: "Ficar sozinho", icon: "🚪" },
      { value: "vet", label: "Veterinário e banho", icon: "🏥" },
      { value: "nothing", label: "Nada, ele é de boa", icon: "😎" },
    ],
  },
  {
    key: "reward_for_good_behavior",
    type: "list",
    title: "O que ele faz por uma recompensa?",
    subtitle: "Isso define a moeda do treino.",
    options: [
      { value: "food", label: "Qualquer coisa por comida", icon: "🍖" },
      { value: "toy", label: "Enlouquece por brinquedo", icon: "🎾" },
      { value: "praise", label: "Vive por carinho e elogio", icon: "🥰" },
      { value: "play", label: "Prefere correr e brincar", icon: "🏃" },
    ],
  },
  {
    key: "motivation_during_training",
    type: "list",
    title: "Quanto tempo ele mantém o foco?",
    options: [
      { value: "seconds", label: "Alguns segundos", icon: "⏱️" },
      { value: "few-minutes", label: "Uns 2 a 3 minutos", icon: "⏳" },
      { value: "long", label: "Mais de 5 minutos", icon: "🎯" },
      { value: "unknown", label: "Nunca reparei", icon: "🤷" },
    ],
  },
  {
    key: "science",
    type: "static",
    variant: "science",
    title: "Por que 10 minutos funcionam melhor",
    body: "Cães aprendem por repetição curta e frequente, não por maratona. Sessões breves e diárias fixam o comportamento — é assim que o cérebro dele consolida o que aprendeu.",
    bullets: [
      "Reforço positivo, sem coleira de choque",
      "Baseado em ciência do comportamento animal",
      "Construído por adestradores certificados",
    ],
    cta: "Entendi",
  },
  {
    key: "reliable_obedience",
    type: "list",
    title: "Ele obedece mesmo com distração por perto?",
    options: [
      { value: "home-only", label: "Só em casa, sem distração", icon: "🏠" },
      { value: "sometimes", label: "Depende do dia", icon: "🎲" },
      { value: "mostly", label: "Quase sempre", icon: "💪" },
      { value: "never", label: "Nunca testei", icon: "❓" },
    ],
  },
  {
    key: "did_you_hear",
    type: "list",
    title: "Como você chegou até o AlphaDog?",
    options: [
      { value: "instagram", label: "Instagram" },
      { value: "youtube", label: "YouTube" },
      { value: "tiktok", label: "TikTok" },
      { value: "google", label: "Google" },
      { value: "friend", label: "Indicação de amigo" },
      { value: "other", label: "Outro" },
    ],
  },
  {
    key: "reviewed",
    type: "static",
    variant: "reviewed",
    title: "Revisado por quem entende",
    body: "Todo o conteúdo do AlphaDog passa por adestradores e um médico-veterinário especialista em comportamento antes de chegar até você.",
    cta: "Continuar",
  },
  {
    key: "ask_qualified_handler",
    type: "list",
    title: "Já pensou em contratar um adestrador?",
    options: [
      { value: "too-expensive", label: "Sim, mas é caro demais", icon: "💸" },
      { value: "tried", label: "Já contratei antes", icon: "🔁" },
      { value: "no-time", label: "Não tenho horário que encaixe", icon: "🕐" },
      { value: "prefer-myself", label: "Prefiro treinar eu mesmo", icon: "🙋" },
    ],
  },
  {
    key: "motivation_during_challenges",
    type: "list",
    title: "Quando o treino trava, o que te faz continuar?",
    options: [
      { value: "progress", label: "Ver progresso, mesmo pequeno", icon: "📈" },
      { value: "routine", label: "Ter uma rotina clara", icon: "📋" },
      { value: "support", label: "Poder perguntar para alguém", icon: "💬" },
      { value: "results", label: "Prazo e meta definidos", icon: "🎯" },
    ],
  },
  {
    key: "optimal_training_moments",
    type: "list",
    multiple: true,
    title: "Quando dá para treinar?",
    subtitle: "Vamos encaixar o plano na sua rotina.",
    options: [
      { value: "morning", label: "De manhã", icon: "🌅" },
      { value: "lunch", label: "No almoço", icon: "☀️" },
      { value: "evening", label: "Fim de tarde", icon: "🌇" },
      { value: "night", label: "À noite", icon: "🌙" },
      { value: "weekend", label: "Só no fim de semana", icon: "📆" },
    ],
  },
  {
    key: "petName",
    type: "text",
    title: "Como ele se chama?",
    subtitle: "Vamos usar o nome dele no plano.",
    placeholder: "Nome do seu cão",
    maxLength: 24,
  },
  {
    key: "profile",
    type: "profile",
    title: "Este é o perfil do seu cão",
    cta: "Continuar",
  },
  {
    key: "time_ready_to_spend",
    type: "list",
    title: "Quanto tempo por dia você tem?",
    subtitle: "Seja realista — constância vale mais que volume.",
    options: [
      { value: "5", label: "5 minutos", hint: "O essencial", icon: "⚡" },
      { value: "10", label: "10 minutos", hint: "O ideal", icon: "⭐" },
      { value: "20", label: "20 minutos", hint: "Evolução rápida", icon: "🚀" },
      { value: "30", label: "30 minutos ou mais", hint: "Modo intensivo", icon: "🔥" },
    ],
  },
  {
    key: "support",
    type: "static",
    variant: "support",
    title: "Feito para caber no seu dia",
    body: "Nada de curso gravado que você nunca termina. O AlphaDog diz o que treinar hoje, mostra como, e acompanha a evolução com você.",
    cta: "Montar meu plano",
  },
  {
    key: "magic",
    type: "loading",
    title: "Montando o plano do seu cão",
    phases: [
      "Analisando raça e fase de vida",
      "Cruzando comportamento e gatilhos",
      "Definindo a moeda de recompensa",
      "Ordenando a trilha de treino",
      "Ajustando ao seu tempo disponível",
    ],
  },
  {
    key: "email",
    type: "email",
    title: "Para onde enviamos o plano?",
    subtitle: "Você vai usar este e-mail para acessar o programa.",
    placeholder: "seu@email.com.br",
    cta: "Ver meu plano",
    disclaimer:
      "Seus dados ficam protegidos. Nada de spam — só o que importa para o treino do seu cão.",
  },
  {
    key: "email_subscription",
    type: "confirm",
    title: "Quer receber dicas de treino por e-mail?",
    subtitle:
      "Uma dica curta por semana, no nível do seu cão. Dá para sair quando quiser.",
    cta: "Pode mandar",
    declineLabel: "Agora não",
  },
  {
    key: "scratch-card",
    type: "scratch-card",
    title: "Você desbloqueou uma raspadinha",
    subtitle: "Raspe para descobrir o seu desconto.",
    cta: "Continuar",
  },
] as const;

export const FUNNEL_SLUG = "alphadog-v1";
